```
createOrReplace

    table INFLUENZA
        lineageTag: b7cff6a8-c974-4cae-8fc5-de4c8a63f236
        column 'Week Ending (Friday)'
            dataType: datetime
            lineageTag: c78f148f-d4e8-4539-a99e-f307967202c5
            summarizeBy: none
            sourceColumn: "Week Ending (Friday)"
            annotation SummarizationSetBy = Automatic

        column 'STATE'
            dataType: string
            lineageTag: de6ca28f-fec3-43ef-ac59-d8100d796302
            summarizeBy: none
            sourceColumn: STATE
            annotation SummarizationSetBy = Automatic

        column 'Age  group'
            dataType: string
            lineageTag: f6202de1-1c5d-4b22-be91-20bdf5e8aa91
            summarizeBy: none
            sourceColumn: 'Age  group'
            annotation SummarizationSetBy = Automatic

        column 'SEX'
            dataType: string
            lineageTag: 84cee5a4-5c00-4b04-91b1-2198a4b886b5
            summarizeBy: none
            sourceColumn: SEX
            annotation SummarizationSetBy = Automatic

        column 'Indigenous status'
            dataType: string
            lineageTag: e034f96e-7e6a-4e13-bc20-24246dfa9b6c
            summarizeBy: none
            sourceColumn: 'Indigenous status'
            annotation SummarizationSetBy = Automatic

        column 'Type/Subtype'
            dataType: string
            lineageTag: 714db991-0450-4d21-8145-640a104a6ca9
            summarizeBy: none
            sourceColumn: 'Type/Subtype'
            annotation SummarizationSetBy = Automatic

        column 'Year'
            dataType: int64
            lineageTag: 6fca95b5-7985-4734-a1d5-3549521ee412
            summarizeBy: sum
            sourceColumn: Year
            annotation SummarizationSetBy = Automatic

        column 'Month'
            dataType: int64
            lineageTag: ba33573b-ad31-4501-8471-8afa1fda5135
            summarizeBy: sum
            sourceColumn: Month
            annotation SummarizationSetBy = Automatic

        partition INFLUENZA = m
            mode: directQuery
            source =
                let
                    Source = Snowflake.Databases("hf97758.australia-east.azure.snowflakecomputing.com","COMPUTE_WH"),
                    HealthCareDatabase = Source{[ Name="HEALTHCARE", Kind="Database"]}[Data],
                    PUBLIC_Schema = HealthCareDatabase{[ Name="PUBLIC",Kind="Schema"]}[Data],
                    INFLUENZA_Table = PUBLIC_Schema{[ Name="INFLUENZA", Kind="Table"]}[Data]
                in
                    INFLUENZA_Table

        annotation PBI_NavigationStepName = Navigation
        annotation PBI_ResultType = Table
        measure 'Yearly Influenza Cases by Type' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Type/Subtype] IN {"A(H3N2)", "A(H1N1)pdm09", "A(H1N1)", "A and B"}))
          formatString: 0
          lineageTag: c2f8f8d9-2603-4005-84df-914568256b73

        measure 'Total Cases by Year' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) > 0))
          formatString: 0
          lineageTag: a8e95483-202-4525-b2a2-b2418fdbde4c

        measure 'Monthly Trends by Year' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = YEAR(TODAY())))
          formatString: 0
          lineageTag: 42721487-f1de-4a90-84bc-fc96ab3194b

        measure 'Total Cases By Age Group' = COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: uHshkc

        measure 'Yearly influenza Analysis By different Types' = 
          COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) IN {2016,2010,2013,2014,2015,2017,2018,2022,2023,2008,2009}))
          - COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = YEAR(TODAY())-1))
          formatString: 0
          lineageTag: GdTrKT

        measure 'Cases across different states' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[STATE] IN {"ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"}))
          formatString: 0
          lineageTag: DTvme

        measure 'Cases' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = YEAR(TODAY())))
          formatString: 0
          lineageTag: Cszqju

        measure 'Monthly Comparison of Cases' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = MAX('INFLUENZA'[Year])))
          formatString: 0
          lineageTag: mpqxkR

        measure 'Total Cases by Month Name' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = MAX('INFLUENZA'[Year])))
          formatString: 0
          lineageTag: kzPmMBY

        measure 'State Wise Analysis of Influenza Cases' = COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: GJFP

        measure 'Indigenous Status Analysis' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Indigenous status] = "Indigenous")) / COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: eTagPW

        measure 'Year over Year change' = 
          DIVIDE(SUMX(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = MAX('INFLUENZA'[Year])), 'INFLUENZA'[Month]), 
                 SUMX(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = MAX('INFLUENZA'[Year])-1), 'INFLUENZA'[Month]), 0) - 1
          formatString: 0%
          lineageTag: FrtyD

        measure 'Influenza Type along Age Group' = COUNTROWS(FILTER('INFLUENZA', ISBLANK('INFLUENZA'[Age  group]) && ISBLANK('INFLUENZA'[STATE])))
          formatString: 0
          lineageTag: jjrJC

        measure 'Cumulative Cases Over the Latest Year' = 
          SUMX(VALUES('INFLUENZA'[Year]), COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year]))))
          formatString: 0
          lineageTag: jnFuFu

        measure '12-Week Trend of Moving Averages' = 
          AVERAGEX(VALUES('INFLUENZA'[Month]), CALCULATE(COUNTROWS('INFLUENZA'), DATESINPERIOD('INFLUENZA'[Week Ending (Friday)], MAX('INFLUENZA'[Week Ending (Friday)]), -12, WEEK)))
          formatString: 0
          lineageTag: RCHmZwX

        measure 'Rolling 3-Month Average' = 
          AVERAGE(VALUES('INFLUENZA'[Week Ending (Friday)]))
          formatString: 0
          lineageTag: kzPAbHy
```