```yaml
createOrReplace

    table Main
        lineageTag: fbc12345-6789-0abc-def1-23456789abcd
        column date
            dataType: datetime
            lineageTag: 1a2b3c4d-5e6f-7g8h-9i0j-k12345678901
            summarizeBy: none
            sourceColumn: Date
            annotation SummarizationSetBy = Automatic

        column 'Employee-Sales'
            dataType: string
            lineageTag: 2b3c4d5e-6f7g-8h9i-0j1k-l23456789012
            summarizeBy: none
            sourceColumn: EmpID
            annotation SummarizationSetBy = Automatic

        column Name
            dataType: string
            lineageTag: 3c4d5e6f-7g8h-9i0j-1k2l-m34567890123
            summarizeBy: none
            sourceColumn: Name
            annotation SummarizationSetBy = Automatic

        partition Main = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx],
                    ChangedType = Table.TransformColumnTypes(Source,{{"Date", type datetime}, {"EmpID", type text}, {"Total Sales", type number}, {"Total Units", type number}})
                in
                    ChangedType
        annotation PBI_NavigationStepName = Data Management
        annotation PBI_ResultType = Table
        measures:
          - name: 'Best Performing Employee (Highest Sales)'
            expression: FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), EmpID))
            formatString: 0
            lineageTag: a1b2c3d4-5e6f-7g8h-9i0j-k12345678901
          - name: 'Highest Sales Location'
            expression: FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), EmpID))
            formatString: 0
            lineageTag: b2c3d4e5-6f7g-8h9i-0j1k-l23456789012
          - name: 'Sales per Day'
            expression: SUM([Total Sales]) / COUNT(DISTINCT [Date])
            formatString: 0
            lineageTag: c3d4e5f6-7g8h-9i0j-1k2l-m34567890123
          - name: 'Units Sold per Transaction'
            expression: SUM([Total Units]) / COUNT([Total Units])
            formatString: 0
            lineageTag: d4e5f6g7-8h9i-0j1k-2l3m-n45678901234
          - name: 'Sales per Employee per Location'
            expression: SUM([Total Sales]) / COUNT(DISTINCT [Employee-Sales])
            formatString: 0
            lineageTag: e5f6g7h8-9i0j-1k2l-3m4n-o56789012345
```