```yaml
createOrReplace

    table Main
        lineageTag: b7cff6a8-c974-4cae-8fc5-de4c8a63f236
        column 'date'
            dataType: datetime
            lineageTag: c78f148f-d4e8-4539-a99e-f307967202c5
            summarizeBy: none
            sourceColumn: date
            annotation SummarizationSetBy = Automatic

        column 'Employee-Sales'
            dataType: string
            lineageTag: de6ca28f-fec3-43ef-ac59-d8100d796302
            summarizeBy: none
            sourceColumn: EmpID
            annotation SummarizationSetBy = Automatic

        column 'Name'
            dataType: string
            lineageTag: f6202de1-1c5d-4b22-be91-20bdf5e8aa91
            summarizeBy: none
            sourceColumn: Name
            annotation SummarizationSetBy = Automatic

        column 'Location-Sales'
            dataType: string
            lineageTag: 84cee5a4-5c00-4b04-91b1-2198a4b886b5
            summarizeBy: none
            sourceColumn: LocId
            annotation SummarizationSetBy = Automatic

        column 'Total Sales'
            dataType: float
            lineageTag: e034f96e-7e6a-4e13-bc20-24246dfa9b6c
            summarizeBy: sum
            sourceColumn: Total Sales
            annotation SummarizationSetBy = Automatic

        column 'Total Units'
            dataType: int64
            lineageTag: 714db991-0450-4d21-8145-640a104a6ca9
            summarizeBy: sum
            sourceColumn: Total Units
            annotation SummarizationSetBy = Automatic

        partition Employees = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx],
                    ChangedType = Table.TransformColumnTypes(Source,{{"EmpID", type text}, {"Name", type text}})
                in
                    ChangedType

        partition Sales = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx],
                    ChangedType = Table.TransformColumnTypes(Source,{{"EmpID", type text}, {"LocId", type text}, {"Total Sales", type number}, {"Total Units", type number}, {"Date", type date}})
                in
                    ChangedType

        partition Locations = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx],
                    ChangedType = Table.TransformColumnTypes(Source,{{"LocId", type text}, {"City", type text}})
                in
                    ChangedType

        annotation PBI_NavigationStepName = Navigation
        annotation PBI_ResultType = Table
        measure 'Best Performing Employee (Highest Sales)' = FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), 'Employee-Sales'))
          formatString: $ #,0
          lineageTag: c2f8f8d9-2603-4005-84df-914568256b73

        measure 'Highest Sales Location' = FirstSortedValue([Location-Sales], -Aggr(SUM([Total Sales]), 'Employee-Sales'))
          formatString: $ #,0
          lineageTag: a8e95483-202-4525-b2a2-b2418fdbde4c

        measure 'Sales per Day' = SUM([Total Sales]) / COUNT(DISTINCT [Date])
          formatString: $ #,0
          lineageTag: 42721487-f1de-4a90-84bc-fc96ab3194b

        measure 'Units Sold per Transaction' = SUM([Total Units]) / COUNT([Total Units])
          formatString: 0
          lineageTag: 12345678-1234-1234-1234-123456789012

        measure 'Sales per Employee per Location' = SUM([Total Sales]) / COUNT(DISTINCT [Employee-Sales])
          formatString: $ #,0
          lineageTag: 87654321-4321-4321-4321-210987654321
```