```yaml
createOrReplace

    table Main
        lineageTag: e2d20427-e048-4710-bb79-baa1c4f7c689
        column name
            dataType: string
            lineageTag: d36d5875-12b7-4b12-a5ee-0df7c76597cf
            summarizeBy: none
            sourceColumn: name
            annotation SummarizationSetBy = Automatic
        partition Employees = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx]
                    Employees = Source{[Name="Employees"]}[Data]
                in
                    Employees
        partition Sales = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx]
                    Sales = Source{[Name="Sales"]}[Data]
                in
                    Sales
        partition Locations = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx]
                    Locations = Source{[Name="Locations"]}[Data]
                in
                    Locations
        annotation PBI_NavigationStepName = Main
        annotation PBI_ResultType = Table
        measure 'Best Performing Employee (Highest Sales)' = FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), [Employee-Sales]))
          formatString: 0
          lineageTag: 25b49346-5f1b-482c-aebc-11243794eb45
        measure 'Highest Sales Location' = FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), [Employee-Sales]))
          formatString: 0
          lineageTag: 1e01c29d-0455-4143-897e-f29bdbdb20b8
        measure 'Sales per Day' = SUM([Total Sales]) / COUNT(DISTINCT [Date])
          formatString: 0
          lineageTag: e66c4725-659d-4d6c-90eb-e1c5bb12cc67
        measure 'Units Sold per Transaction' = SUM([Total Units]) / COUNT([Total Units])
          formatString: 0
          lineageTag: df66e6bc-4910-459d-b605-f45e03e10ad7
        measure 'Sales per Employee per Location' = SUM([Total Sales]) / COUNT(DISTINCT [Employee-Sales])
          formatString: 0
          lineageTag: 5fb39654-90f5-41a2-9477-c407e174529c
```