createOrReplace

    table Main
        lineageTag: b7cff6a8-c974-4cae-8fc5-de4c8a63f236
        column name
            dataType: string
            lineageTag: d23af865-ff3b-49c2-bba6-8b456fc88c61
            summarizeBy: none
            sourceColumn: name
            annotation SummarizationSetBy = Automatic
        partition __cityAliasesBase = m
            mode: import
            source =
                let
                    Alias = 'Alias',
                    geoKey = 'geoKey',
                    CountryCode = 'CountryCode'
                in
                    [
                      {
                        "Alias": "New York",
                        "geoKey": "12345",
                        "CountryCode": "US"
                      },
                      {
                        "Alias": "Los Angeles",
                        "geoKey": "54321",
                        "CountryCode": "US"
                      }
                    ]
        partition __cityGeoBase = m
            mode: import
            source =
                let
                    geoKey = 'geoKey',
                    geoPoint = 'geoPoint'
                in
                    [
                      {
                        "geoKey": "12345",
                        "geoPoint": "40.7128,-74.0060"
                      },
                      {
                        "geoKey": "54321",
                        "geoPoint": "34.0522,-118.2437"
                      }
                    ]
        partition [Employees] = m
            mode: import
            source =
                let
                    EmpID = 'EmpID',
                    Name = 'Name'
                in
                    [
                      {
                        "EmpID": 1,
                        "Name": "John Doe"
                      },
                      {
                        "EmpID": 2,
                        "Name": "Jane Smith"
                      }
                    ]
        partition [Sales] = m
            mode: import
            source =
                let
                    EmpID = 'EmpID',
                    LocId = 'LocId',
                    Date = 'Date',
                    Total_Sales = 'Total Sales',
                    Total_Units = 'Total Units'
                in
                    [
                      {
                        "EmpID": 1,
                        "LocId": "A",
                        "Date": "01/01/2023",
                        "Total Sales": 100,
                        "Total Units": 5
                      },
                      {
                        "EmpID": 2,
                        "LocId": "B",
                        "Date": "01/02/2023",
                        "Total Sales": 150,
                        "Total Units": 8
                      }
                    ]
        partition [Locations] = m
            mode: import
            source =
                let
                    LocId = 'LocId',
                    City = 'City'
                in
                    [
                      {
                        "LocId": "A",
                        "City": "New York"
                      },
                      {
                        "LocId": "B",
                        "City": "Los Angeles"
                      }
                    ]
        annotation PBI_NavigationStepName = Main
        annotation PBI_ResultType = Table
        measure 'Best Performing Employee (Highest Sales)' = FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), [Employee-Sales]))
          formatString: $ #,0
          lineageTag: c2f8f8d9-2603-4005-84df-914568256b73
        measure 'Highest Sales Location' = FirstSortedValue([Employee-Sales], -Aggr(SUM([Total Sales]), [Employee-Sales]))
          formatString: $ #,0
          lineageTag: a8e95483-202-4525-b2a2-b2418fdbde4c
        measure 'Sales per Day' = SUM([Total Sales]) / COUNT(DISTINCT [Date])
          formatString: $ #,0
          lineageTag: 42721487-f1de-4a90-84bc-fc96ab3194b
        measure 'Units Sold per Transaction' = SUM([Total Units]) / COUNT([Total Units])
          formatString: #,0.00
          lineageTag: c4f813e1-f105-41d5-8a9f-07c8e66bc40b
        measure 'Sales per Employee per Location' = SUM([Total Sales]) / COUNT(DISTINCT [Employee-Sales])
          formatString: $ #,0
          lineageTag: 33ad0454-f012-46af-ae03-33ad45c012a3