table Alcoholregionsfinal
	lineageTag: 80026c3f-38e1-4fb5-b04a-5f33a48583e8

	measure 'Total Deaths' = SUM(Alcoholregionsfinal[Deaths])
		formatString: 0
		lineageTag: 2382f046-e900-4c13-9fe7-92e8cb9a78a4

	column Year
		dataType: string
		lineageTag: 826009ad-19ff-4ce1-9aa6-b50cca7411c5
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column ICD_10_code
		dataType: string
		lineageTag: f42e2747-47ad-43cf-8420-4ed759d618c3
		summarizeBy: none
		sourceColumn: ICD_10_code

		annotation SummarizationSetBy = Automatic

	column Individual_cause_of_death_description
		dataType: string
		lineageTag: fa2e335c-5e78-459c-b867-cea556d29fe2
		summarizeBy: none
		sourceColumn: Individual_cause_of_death_description

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 014734f5-093b-417d-babc-2bfd1caf3bc6
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age_Groups
		dataType: string
		lineageTag: 2bcda326-c5c8-4ea9-bd3e-aa92f74d3839
		summarizeBy: none
		sourceColumn: Age_Groups

		annotation SummarizationSetBy = Automatic

	column Age_Groups_Index
		dataType: string
		lineageTag: f83b7017-5583-4d0c-929c-f79e238c4b2b
		summarizeBy: none
		sourceColumn: Age_Groups_Index

		annotation SummarizationSetBy = Automatic

	column Deaths
		dataType: int64
		formatString: 0
		lineageTag: dfd3c178-061b-4649-a222-66f31a6998ec
		summarizeBy: sum
		sourceColumn: Deaths

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 1744c1d0-dfce-44c3-b34f-d50be3a3d42b
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition Alcoholregionsfinal = m
		mode: import
		source =
				let
				    Source = Sql.Databases("health-careserver.database.windows.net"),
				    #"Alcohol-specific deaths in uk" = Source{[Name="Alcohol-specific deaths in uk"]}[Data],
				    dbo_Alcoholregionsfinal = #"Alcohol-specific deaths in uk"{[Schema="dbo",Item="Alcoholregionsfinal"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Alcoholregionsfinal,{{"Year", type text}, {"Deaths", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Gender] <> "Persons") and ([Location] <> "Location"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
