```yaml
createOrReplace

    table INFLUENZA
        lineageTag: c69ef645-bad0-485e-a6cd-e3dc08136b1d
        column 'Week Ending (Friday)'
            dataType: datetime
            lineageTag: c4f91771-d515-499b-b94b-b3c61de98702
            summarizeBy: none
            sourceColumn: Week Ending (Friday)
            annotation SummarizationSetBy = Automatic

        column 'STATE'
            dataType: string
            lineageTag: c71bb376-d1da-4486-b64e-a38238a92ff9
            summarizeBy: none
            sourceColumn: STATE
            annotation SummarizationSetBy = Automatic

        column 'Age  group'
            dataType: string
            lineageTag: e004f17f-b63c-4dd7-9174-e95d5391fb63
            summarizeBy: none
            sourceColumn: Age  group
            annotation SummarizationSetBy = Automatic

        column 'SEX'
            dataType: string
            lineageTag: f594c44f-c09e-4876-bd69-e82c670497a2
            summarizeBy: none
            sourceColumn: SEX
            annotation SummarizationSetBy = Automatic

        column 'Indigenous status'
            dataType: string
            lineageTag: cbbc623d-c149-4630-a203-daeacee44486
            summarizeBy: none
            sourceColumn: Indigenous status
            annotation SummarizationSetBy = Automatic

        column 'Type/Subtype'
            dataType: string
            lineageTag: b792ba91-b73e-4085-afcb-9642518dcce2
            summarizeBy: none
            sourceColumn: Type/Subtype
            annotation SummarizationSetBy = Automatic

        column 'Year'
            dataType: int64
            lineageTag: 52c9d08e-5bd1-4ce2-bd77-24dc4a65875e
            summarizeBy: none
            sourceColumn: Year
            annotation SummarizationSetBy = Automatic

        column 'Month'
            dataType: string
            lineageTag: e0a8e837-74fa-42a9-a1ed-d73207424f65
            summarizeBy: none
            sourceColumn: Month
            annotation SummarizationSetBy = Automatic

        partition INFLUENZA = m
            mode: directQuery
            source =
                let
                    Source = Snowflake.Databases("hf97758.australia-east.azure.snowflakecomputing.com","HEALTHCARE"),
                    HealthCareDatabase = Source{[ Name="HEALTHCARE", Kind="Database"]}[Data],
                    PUBLIC_Schema = HealthCareDatabase{[ Name="PUBLIC",Kind="Schema"]}[Data],
                    INFLUENZA_Table = PUBLIC_Schema{[ Name="INFLUENZA", Kind="Table"]}[Data]
                in
                    INFLUENZA_Table

        annotation PBI_NavigationStepName = Navigation
        annotation PBI_ResultType = Table
        measure 'Yearly Influenza Cases by Type' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Type/Subtype] IN {"A(H3N2)", "A(H1N1)pdm09", "A(H1N1)", "A and B"}))
          formatString: 0
          lineageTag: 45748571-3425-470d-86ed-517263761bfa

        measure 'Total Cases by Year' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) > 0))
          formatString: 0
          lineageTag: 120d04c3-b1c5-4c15-816e-48a713f56bb5

        measure 'Monthly Trends by Year' = COUNTROWS(FILTER('INFLUENZA', YEAR('INFLUENZA'[Week Ending (Friday)]) = YEAR(TODAY())))
          formatString: 0
          lineageTag: 3fe23f63-83f9-40d4-af0a-b056e8b11ca4

        measure 'Total Cases By Age Group' = COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: c37123eb-b893-446f-b6da-9e9be8760be9

        measure 'Yearly influenza Analysis By different Types' = 
          COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] IN {2016, 2010, 2013, 2014, 2015, 2017, 2018, 2022, 2023, 2008, 2009} && MONTH('INFLUENZA'[Week Ending (Friday)]) = MONTH(TODAY())))
          formatString: 0
          lineageTag: b2206899-69cf-4812-921b-f4a953488a61

        measure 'Cases across different states' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[STATE] IN {"ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"}))
          formatString: 0
          lineageTag: 2a8fdef4-f73d-477f-8435-f2fb18b48573

        measure 'Cases' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = YEAR(TODAY())))
          formatString: 0
          lineageTag: d755bc1b-cf05-4cc9-afc3-982ad706d98e

        measure 'Monthly Comparison of Cases' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year])))
          formatString: 0
          lineageTag: 5c36817d-2063-44cb-b70b-996298192606

        measure 'Total Cases by Month Name' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year])))
          formatString: 0
          lineageTag: 8cc55494-0132-4486-9775-b42b471573fa

        measure 'State Wise Analysis of Influenza Cases' = COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: d0de5290-f60d-49a2-b120-3a81ff10d77c

        measure 'Indigenous Status Analysis' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Indigenous status] = "Indigenous")) / COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: cdfc3422-fca5-4dbd-b962-cb7814915404

        measure 'Year over Year change' = 
          SUM(FILTER('INFLUENZA', YEAR('INFLUENZA'[Year]) = MAX('INFLUENZA'[Year]))) / 
          SUM(FILTER('INFLUENZA', YEAR('INFLUENZA'[Year]) = MAX('INFLUENZA'[Year]) - 1)) - 1
          formatString: 0%
          lineageTag: e3150c06-1199-41bc-b63d-b80ef8ac0833

        measure 'Influenza Type along Age Group' = COUNTROWS(FILTER('INFLUENZA', ISBLANK('INFLUENZA'[Age  group]) && 'INFLUENZA'[STATE]))
          formatString: 0
          lineageTag: d54fd31b-6073-46ed-a802-2042448db8e2

        measure 'Cumulative Cases Over the Latest Year' = 
          RANGE_SUM(ABOVE(COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year]))), 0, ROW_NO()))
          formatString: 0
          lineageTag: 844bcac8-09b1-4679-b676-d9d02b452059

        measure '12-Week Trend of Moving Averages' = 
          AVERAGE(ABOVE(COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year]))), 0, 12))
          formatString: 0
          lineageTag: f1f72eb0-cfb0-451b-b28e-73ea515bb29c

        measure 'Rolling 3-Month Average' = 
          AVERAGE(AGGR(
              RANGE_AVG(ABOVE(SUM('INFLUENZA'[Week Ending (Friday)]), 0, 3)), 
              'INFLUENZA'[Month]
          ))
          formatString: 0
          lineageTag: 2cb16f8c-b1bb-4e6c-835e-a013b9025390
```