```yaml
createOrReplace

    table INFLUENZA
        lineageTag: 893adfe1-aba7-4180-a394-44ed62b65394
        column 'Week Ending (Friday)'
            dataType: datetime
            lineageTag: 33ac9942-e289-41d4-98c9-c05d00fb8be6
            summarizeBy: none
            sourceColumn: Week Ending (Friday)
            annotation SummarizationSetBy = Automatic

        column 'STATE'
            dataType: string
            lineageTag: 58123cb9-84fa-4ff3-9c58-074ba63ac651
            summarizeBy: none
            sourceColumn: STATE
            annotation SummarizationSetBy = Automatic

        column 'Age  group'
            dataType: string
            lineageTag: e6122d2d-0aa5-4617-a301-fec7672035cc
            summarizeBy: none
            sourceColumn: Age  group
            annotation SummarizationSetBy = Automatic

        column 'SEX'
            dataType: string
            lineageTag: 101eec06-f61b-4aa1-a517-5e27779e2c76
            summarizeBy: none
            sourceColumn: SEX
            annotation SummarizationSetBy = Automatic

        column 'Indigenous status'
            dataType: string
            lineageTag: ef58e514-c623-4976-af69-bde10975ff6d
            summarizeBy: none
            sourceColumn: Indigenous status
            annotation SummarizationSetBy = Automatic

        column 'Type/Subtype'
            dataType: string
            lineageTag: d5c751e1-4ee5-40e0-a0f7-fdb415027688
            summarizeBy: none
            sourceColumn: Type/Subtype
            annotation SummarizationSetBy = Automatic

        column 'Year'
            dataType: int64
            lineageTag: 614179e0-dbb4-434d-87b0-fb993408a342
            summarizeBy: none
            sourceColumn: Year
            annotation SummarizationSetBy = Automatic

        column 'Month'
            dataType: int64
            lineageTag: 44053b09-74cf-4716-af88-16508e454c3b
            summarizeBy: none
            sourceColumn: Month
            annotation SummarizationSetBy = Automatic

        partition INFLUENZA = m
            mode: import
            source =
                let
                    Source = Snowflake.Databases("hf97758.australia-east.azure.snowflakecomputing.com","HEALTHCARE"),
                    InfluenzaTable = Source{[Name="PUBLIC", Kind="Schema"]}{[Name="INFLUENZA", Kind="Table"]}[Data]
                in
                    InfluenzaTable
        annotation PBI_NavigationStepName = Navigation
        annotation PBI_ResultType = Table
        measure 'Yearly Influenza Cases by Type' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Type/Subtype] IN {"A(H3N2)", "A(H1N1)pdm09", "A(H1N1)", "A and B"}))
          formatString: 0
          lineageTag: c9b39dd1-c11e-4e2a-a19b-e60169da2036

        measure 'Total Cases by Year' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] > 0))
          formatString: 0
          lineageTag: 0da2834b-7c3a-4968-9675-49942c765693

        measure 'Monthly Trends by Year' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = YEAR(TODAY())))
          formatString: 0
          lineageTag: 1c45e303-e82c-4042-9bd3-01568e758d8f

        measure 'Total Cases By Age Group' = COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: c26c9738-a10e-40c0-bc43-34dc66cd62a1

        measure 'Yearly influenza Analysis By different Types' = 
            COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] IN {2016, 2010, 2013, 2014, 2015, 2017, 2018, 2022, 2023, 2008, 2009} && MONTH(TODAY()) = MONTH('INFLUENZA'[Week Ending (Friday)]))) 
            - COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] IN {2016, 2010, 2013, 2014, 2015, 2017, 2018, 2022, 2023, 2008, 2009} && MONTH(TODAY()) - 1 = MONTH('INFLUENZA'[Week Ending (Friday)]))
          formatString: 0
          lineageTag: b20c160e-b494-4132-853d-92bc95b43da4

        measure 'Cases across different states' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[STATE] IN {"ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"}))
          formatString: 0
          lineageTag: 78964c41-377d-4406-96cf-59c83663f028

        measure 'Cases' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = YEAR(TODAY())))
          formatString: 0
          lineageTag: e850eef8-b761-41eb-bdf4-01752ea688c2

        measure 'Monthly Comparison of Cases' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year])))
          formatString: 0
          lineageTag: 62bb9072-c9f5-44ec-bdf9-f37d17143867

        measure 'Total Cases by Month Name' = COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year])))
          formatString: 0
          lineageTag: aabc65d2-c19c-4768-b657-e032947bf051

        measure 'State Wise Analysis of Influenza Cases' = COUNTROWS('INFLUENZA')
          formatString: 0
          lineageTag: a89abdf2-d61e-4399-bd59-d3182748ab83

        measure 'Indigenous Status Analysis' = DIVIDE(COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Indigenous status] = "Indigenous")), COUNTROWS('INFLUENZA'))
          formatString: 0.0%
          lineageTag: f1693bb3-073e-4295-afc3-824726cb6917

        measure 'Year over Year change' = 
            DIVIDE(
                SUMX(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year])), 'INFLUENZA'[Month]),
                SUMX(FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year]) - 1), 'INFLUENZA'[Month])
            ) - 1
          formatString: 0%
          lineageTag: 0774424b-5406-411d-b1e8-b9c58277a78b

        measure 'Influenza Type along Age Group' = COUNTROWS(FILTER('INFLUENZA', ISBLANK('INFLUENZA'[Age  group]) && NOT ISBLANK('INFLUENZA'[STATE])))
          formatString: 0
          lineageTag: 2bc772f7-3307-49b2-83aa-24353efb4554

        measure 'Cumulative Cases Over the Latest Year' = 
            SUMX(
                FILTER('INFLUENZA', 'INFLUENZA'[Year] = MAX('INFLUENZA'[Year])),
                COUNTROWS(FILTER('INFLUENZA', 'INFLUENZA'[Week Ending (Friday)]))
            )
          formatString: 0
          lineageTag: e12557e2-3992-497f-898d-bde7468bc162

        measure '12-Week Trend of Moving Averages' = 
            AVERAGEX(
                DATESINPERIOD('INFLUENZA'[Week Ending (Friday)], LASTDATE('INFLUENZA'[Week Ending (Friday)]), -12, WEEK),
                COUNTROWS('INFLUENZA')
            )
          formatString: 0
          lineageTag: 474d907f-4784-4979-bccc-3791688e354f

        measure 'Rolling 3-Month Average' = 
            AVERAGEX(
                DATESINPERIOD('INFLUENZA'[Week Ending (Friday)], LASTDATE('INFLUENZA'[Week Ending (Friday)]), -3, MONTH),
                SUM('INFLUENZA'[Week Ending (Friday)])
            )
          formatString: 0
          lineageTag: df90edee-2051-4233-80d5-f1c099db70fa
```