```yaml
createOrReplace

    name: Main
    type: script
    content:
        - name: Hospital_ER
          lineageTag: b7cff6a8-c974-4cae-8fc5-de4c8a63f236
          columns:
            - name: date
              dataType: datetime
              lineageTag: c78f148f-d4e8-4539-a99e-f307967202c5
              summarizeBy: none
              sourceColumn: date
              annotation: SummarizationSetBy = Automatic
            - name: patient_id
              dataType: string
              lineageTag: de6ca28f-fec3-43ef-ac59-d8100d796302
              summarizeBy: none
              sourceColumn: patient_id
              annotation: SummarizationSetBy = Automatic
            - name: patient_gender
              dataType: string
              lineageTag: f6202de1-1c5d-4b22-be91-20bdf5e8aa91
              summarizeBy: none
              sourceColumn: patient_gender
              annotation: SummarizationSetBy = Automatic
            - name: patient_age
              dataType: int64
              lineageTag: 84cee5a4-5c00-4b04-91b1-2198a4b886b5
              summarizeBy: sum
              sourceColumn: patient_age
              annotation: SummarizationSetBy = Automatic
            - name: patient_sat_score
              dataType: int64
              lineageTag: e034f96e-7e6a-4e13-bc20-24246dfa9b6c
              summarizeBy: sum
              sourceColumn: patient_sat_score
              annotation: SummarizationSetBy = Automatic
            - name: patient_first_inital
              dataType: string
              lineageTag: 714db991-0450-4d21-8145-640a104a6ca9
              summarizeBy: none
              sourceColumn: patient_first_inital
              annotation: SummarizationSetBy = Automatic
            - name: patient_last_name
              dataType: string
              lineageTag: 6fca95b5-7985-4734-a1d5-3549521ee412
              summarizeBy: none
              sourceColumn: patient_last_name
              annotation: SummarizationSetBy = Automatic
            - name: patient_race
              dataType: string
              lineageTag: ba33573b-ad31-4501-8471-8afa1fda5135
              summarizeBy: none
              sourceColumn: patient_race
              annotation: SummarizationSetBy = Automatic
            - name: patient_admin_flag
              dataType: string
              lineageTag: 79edc306-1a81-471c-822a-de4ae99fa1db
              summarizeBy: none
              sourceColumn: patient_admin_flag
              annotation: SummarizationSetBy = Automatic
            - name: patient_waittime
              dataType: int64
              lineageTag: 0b6027cd-5306-4132-a682-440e98a719c6
              summarizeBy: sum
              sourceColumn: patient_waittime
              annotation: SummarizationSetBy = Automatic
            - name: department_referral
              dataType: string
              lineageTag: 567416f1-2070-42ef-ae44-8a64f4988048
              summarizeBy: none
              sourceColumn: department_referral
              annotation: SummarizationSetBy = Automatic
          partitions:
            - name: Hospital_ER
              mode: import
              source:
                  type: m
                  value: |
                      let
                          Source = Sql.Database("health-careserver.database.windows.net", "health-care2025", [Query="SELECT [date], [patient_id], [patient_gender], [patient_age], [patient_sat_score], [patient_first_inital], [patient_last_name], [patient_race], [patient_admin_flag], [patient_waittime], [department_referral] FROM dbo.Hospital ER"]),
                          ChangedType = Table.TransformColumnTypes(Source,{{"date", type datetime}, {"patient_id", type text}, {"patient_gender", type text}, {"patient_age", Int64.Type}, {"patient_sat_score", type number}, {"patient_first_inital", type text}, {"patient_last_name", type text}, {"patient_race", type text}, {"patient_admin_flag", type text}, {"patient_waittime", type number}, {"department_referral", type text}})
                      in
                          ChangedType
              annotations:
                - name: PBI_NavigationStepName
                  value: Navigation
                - name: PBI_ResultType
                  value: Table
          measures:
            - name: Yearly Influenza Cases by Type
              expression: Count({<Type/Subtype={'A(H3N2)', 'A(H1N1)pdm09', 'A(H1N1)', 'A and B'}>} [Type/Subtype])
              formatString: 0
              lineageTag: pQwjL
            - name: Total Cases by Year
              expression: Count({<year={"*"}>} [Type/Subtype])
              formatString: 0
              lineageTag: pJLFFzU
            - name: Monthly Trends by Year
              expression: Count({<Year = P({$} Year)>} [Type/Subtype])
              formatString: 0
              lineageTag: NAfAGM
            - name: Total Cases By Age Group
              expression: Count(total [Age  group])
              formatString: 0
              lineageTag: TmHbvcF
            - name: Yearly influenza Analysis By different Types
              expression: Count({<Year={2016,2010,2013,2014,2015,2017,2018,2022,2023,2008,2009}, Month={$(=Month(Today()))}>} [Type/Subtype]) - Count({<Year={2016,2010,2013,2014,2015,2017,2018,2022,2023,2008,2009}, Month={$(=Month(Today())-1)}>} [Type/Subtype])
              formatString: 0
              lineageTag: uHshkc
            - name: Cases across different states
              expression: Count({<STATE={'ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA'}>} [Type/Subtype])
              formatString: 0
              lineageTag: GdTrKT
            - name: Cases
              expression: Count({<Year=P({$} Year)>} [Type/Subtype])
              formatString: 0
              lineageTag: UTJJuew
            - name: Monthly Comparison of Cases
              expression: Count({<Year={$(=Max(Year))}>} [Type/Subtype])
              formatString: 0
              lineageTag: Cszqju
            - name: Total Cases by Month Name
              expression: Count({<Year={"$(=Max(Year))"}>} [Type/Subtype])
              formatString: 0
              lineageTag: mpqxkR
            - name: State Wise Analysis of Influenza Cases
              expression: Count(total [Week Ending (Friday)])
              formatString: 0
              lineageTag: kzPmMBY
            - name: Indigenous Status Analysis
              expression: Count({<[Indigenous status]={"Indigenous"}>} [Type/Subtype]) / Count([Type/Subtype])
              formatString: 0
              lineageTag: DTvme
            - name: Year over Year change
              expression: Sum({<Year={"$(=Max(Year))"}>} Month) / Sum({<Year={"$(=Max(Year)-1)"}>} Month) -1
              formatString: 0%
              lineageTag: GJFP
            - name: Influenza Type along Age Group
              expression: COUNT({<Age__group=, STATE=>} Year)
              formatString: 0
              lineageTag: FrtyD
            - name: Cumulative Cases Over the Latest Year
              expression: RangeSum(Above(Count({<Year={"$(=Max(Year))"}>} [Type/Subtype]), 0, RowNo()))
              formatString: 0
              lineageTag: jjrJC
            - name: 12-Week Trend of Moving Averages
              expression: RangeAvg(Above(Count({<Year={"$(=Max(Year))"}>} [Type/Subtype]), 0, 12))
              formatString: 0
              lineageTag: eTagPW
            - name: Rolling 3-Month Average
              expression: Avg(Aggr(RangeAvg(Above(Sum([Week Ending (Friday)]), 0, 3)), Month))
              formatString: 0
              lineageTag: RCHmZwX
```