```
createOrReplace

    table Main
        lineageTag: eefcc091-f7a2-47dc-a348-450ade35d237
        column name
            dataType: string
            lineageTag: 7323f95d-1934-41ee-9307-b304222fcffe
            summarizeBy: none
            sourceColumn: name
            annotation SummarizationSetBy = Automatic
        partition __cityAliasesBase = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/cityAliases.qvd]
                in
                    Source
        partition __cityGeoBase = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/cityGeo.qvd]
                in
                    Source
        partition __cityName2Key = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/cityAliases.qvd]
                in
                    Source
        partition __cityKey2GeoPoint = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/cityGeo.qvd]
                in
                    Source
        partition Employees = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx]
                in
                    Source
        partition Sales = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx]
                in
                    Source
        partition Locations = m
            mode: import
            source =
                let
                    Source = [lib://DataFiles/dataset.xlsx]
                in
                    Source
        annotation PBI_NavigationStepName = Navigation
        annotation PBI_ResultType = Table
        measure 'Best Performing Employee (Highest Sales)' = FirstSortedValue('Employees'[Employee-Sales], -Aggr(SUM('Sales'[Total Sales]), 'Employees'[EmpID]))
          formatString: , 0.00
          lineageTag: a1234567-8c91-4f5b-b591-a5432134e09f
        measure 'Highest Sales Location' = FirstSortedValue('Employees'[Employee-Sales], -Aggr(SUM('Sales'[Total Sales]), 'Employees'[EmpID]))
          formatString: , 0.00
          lineageTag: a9876543-2f98-4d76-bf22-e4443137a123
        measure 'Sales per Day' = SUM('Sales'[Total Sales]) / COUNT(DISTINCT 'Sales'[Date])
          formatString: , 0.00
          lineageTag: f2468a95-074c-456e-bbcc-e0ac57cbb534
        measure 'Units Sold per Transaction' = SUM('Sales'[Total Units]) / COUNT('Sales'[Total Units])
          formatString: , 0.00
          lineageTag: b6427d94-55ba-421d-b441-394fa3f3e0ae
        measure 'Sales per Employee per Location' = SUM('Sales'[Total Sales]) / COUNT(DISTINCT 'Employees'[Employee-Sales])
          formatString: , 0.00
          lineageTag: 03f962b5-b307-407d-af53-b4787da83ff3
```